openapi: 3.0.0
info:
  title: java-rest-api
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /080/api/v1/products:
    post:
      tags:
        - default
      summary: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                name: prodcut one
                quantity: 20
                price: 2000
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                name: prodcut one
                quantity: 50
                price: 2000
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /080/api/v1/products/1:
    delete:
      tags:
        - default
      summary: delete
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
